# Generated by Django 3.0.3 on 2020-03-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
    ]
