# Generated by Django 3.0.3 on 2020-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0003_remove_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
