# Generated by Django 3.0.3 on 2020-03-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0004_profile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
