# Generated by Django 3.0.3 on 2020-03-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0005_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
