# Generated by Django 3.0.3 on 2020-04-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0008_auto_20200323_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
                ('img', models.ImageField(blank=True, upload_to='pics')),
                ('category', models.CharField(choices=[('C', 'Chilli'), ('EA', 'Egg A'), ('EB', 'Egg B'), ('EC', 'Egg C'), ('WS', 'Water Spinach'), ('C', 'Chicken'), ('CS', 'Choy Sum'), ('CO', 'Coconut'), ('TO', 'Tomato')], max_length=200, null=True)),
                ('commodity_type', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=700, null=True)),
            ],
        ),
    ]
