# Generated by Django 3.0.3 on 2020-04-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0010_remove_commodity_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='icon',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
