# Generated by Django 3.0.3 on 2020-04-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0011_commodity_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='farmprice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='marketprice',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commodity',
            name='wholesaleprice',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
