# Generated by Django 3.0.3 on 2020-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0012_auto_20200422_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
