# Generated by Django 3.0.3 on 2020-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0013_commodity_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('commoditytype', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
