# Generated by Django 3.0.3 on 2020-04-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funo', '0014_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
